
package presentacion;

import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import negocio.Comercio;
import negocio.Compra;
import negocio.Item;
import negocio.PresupuestoEnConstruccion;
import negocio.Venta;

public class VentanaNuevaVenta extends javax.swing.JFrame {
    private VentanaPrincipal ventPrinc;
    private Comercio comercio;
    private PresupuestoEnConstruccion presupuesto;
    private DefaultListModel modeloPresupuesto;

    public VentanaNuevaVenta(VentanaPrincipal vp, Comercio c) {
        initComponents();
        ventPrinc=vp;
        comercio=c;
        presupuesto=new PresupuestoEnConstruccion();
        modeloPresupuesto=new DefaultListModel();
        lstDetalleVenta.setModel(modeloPresupuesto);
        

    }
    
    public boolean addItem(Item i){
        return presupuesto.addItem(i);
    }
    
    public void actualizarListadoItems(){
        modeloPresupuesto.clear();
        for(Item iter:presupuesto.getDetallePresupuesto())
            modeloPresupuesto.addElement(iter);
    }
    
    public void actualizarMontoTotal(){
        txtMontoTotal.setText(String.valueOf(presupuesto.montoTotalVenta()));
    }
    
    private void formatoDni(KeyEvent e,JTextField comp){
        char c=e.getKeyChar();
        if(!Character.isDigit(c)&&c!=KeyEvent.VK_BACK_SPACE||comp.getText().trim().length()>=8){
            e.consume();
            getToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(null, "El DNI debe tener 8 digitos y no puede contener puntos");
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDetalleDeArticulos = new javax.swing.JLabel();
        lblNuevaVenta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDetalleVenta = new javax.swing.JList<>();
        btnAgregarItemALaVenta = new javax.swing.JButton();
        lblMontoTotal = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        btnConfirmarVenta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblDniComprador = new javax.swing.JLabel();
        txtDniComprador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nueva Venta");

        lblDetalleDeArticulos.setText("Detalle de articulos:");

        lblNuevaVenta.setText("Nueva Venta en carga:");

        jScrollPane1.setViewportView(lstDetalleVenta);

        btnAgregarItemALaVenta.setText("Agregar Item a la Venta");
        btnAgregarItemALaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarItemALaVentaActionPerformed(evt);
            }
        });

        lblMontoTotal.setText("Monto Total:");

        txtMontoTotal.setEditable(false);

        btnConfirmarVenta.setText("Confirmar Venta");
        btnConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVentaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblDniComprador.setText("D.N.I. del comprador: ");

        txtDniComprador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniCompradorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDetalleDeArticulos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDniComprador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDniComprador))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarItemALaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblNuevaVenta)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMontoTotal)
                                .addGap(22, 22, 22)
                                .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNuevaVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniComprador)
                    .addComponent(txtDniComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblDetalleDeArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMontoTotal)
                    .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarItemALaVenta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarVenta)
                    .addComponent(btnVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ventPrinc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarItemALaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarItemALaVentaActionPerformed
        VentanaNuevoItem vni= new VentanaNuevoItem(this, presupuesto, comercio);
        vni.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgregarItemALaVentaActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
        boolean error=false;
        String dni=txtDniComprador.getText().trim();
        if(dni.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor ingrese el DNI del cliente");
            error=true;
        }
        if(presupuesto.getDetallePresupuesto().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Agregue primero los items a comprar");
            error=true;
        }
        
        if(!error){
            LinkedList<Item> copiaDetPres=new LinkedList(presupuesto.getDetallePresupuesto());
            Venta v=new Venta(dni,copiaDetPres);
            comercio.addVenta(v);
            modeloPresupuesto.clear();
            presupuesto.getDetallePresupuesto().clear();
            txtMontoTotal.setText("");
            txtDniComprador.setText("");
            javax.swing.JOptionPane.showMessageDialog(null, "La venta se registro correctamente");
        }
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void txtDniCompradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniCompradorKeyTyped
        formatoDni(evt,txtDniComprador);
    }//GEN-LAST:event_txtDniCompradorKeyTyped

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarItemALaVenta;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDetalleDeArticulos;
    private javax.swing.JLabel lblDniComprador;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblNuevaVenta;
    private javax.swing.JList<String> lstDetalleVenta;
    private javax.swing.JTextField txtDniComprador;
    private javax.swing.JTextField txtMontoTotal;
    // End of variables declaration//GEN-END:variables
}
